# Generated by Django 3.0.7 on 2020-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
