# Generated by Django 3.0.7 on 2020-06-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200607_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_piece',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
